/*
 * This source file was generated by the Gradle 'init' task
 */
package com.back;

import java.util.Scanner;

public class App {
    static final Scanner scanner = new Scanner(System.in);

    public static void main(String[] args) {
        new WiseSayingCommand().run();
        scanner.close();
    }

}
