/*
 * This source file was generated by the Gradle 'init' task
 */
package com.back;

import java.io.ByteArrayInputStream;

import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    void commandTest() {
        var backup = System.in;
        System.setIn(new ByteArrayInputStream("종료".getBytes()));

        WiseSayingCommand command = new WiseSayingCommand();
        command.run();

        System.setIn(backup);
    }

    @Test
    void runnerTest() {

    }

    @Test
    void storeTest() {

    }

    @Test
    void regexPractice() {
        String str = "삭제?id=자롯";

        var result = str.matches("^삭제\\?id=[1-9]\\d*$");

        System.out.println(result);
    }
}
